---
title: "datavis-R home"
author: "Henrik Husberg"
date: "9/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Weekly excercises

Will be published after the deadlines :)

### Excercise Week 1
```{r}
# Exercises, week 1
# Type your code below the comments. You can add your own comments, too.
# Return this file to Moodle ('firstname_lastname_week1.R').

## Henrik: My comments will look like this.

# Exercise 1: 
# Create a vector named my_vector. It should have 7 numeric elements.

my_vector <- c(4, 6, 9, 2, 5, 3, 1)

# Print your vector.

my_vector

# Calculate the minimum, maximum, and median values of your vector.

summary(my_vector)
median(my_vector)
max(my_vector)
min(my_vector)

# Print "The median value is XX"

paste("The median value is", median(my_vector) )

# Exercise 2: 
# Create another vector named my_vector_2. It should have the elements of my_vector divided by 2.

my_vector_2 <- c(my_vector/2)
my_vector_2

# Create a vector named my_words. It should have 7 character elements.

my_words <- c("a", "b", "c", "d", "e", "f", "g")
my_words

# Combine my_vector and my_words into a data frame.

df <- data.frame(my_vector, my_words)

# Show the structure of the data frame.

str(df)

# Exercise 3:
# Use the head() function to print the first 3 rows of your data frame.

head(df, 3)

# Create a new variable to the data frame which has the values of my_vector_2 (remember to save the new variable to the data frame object).
## Henrik: I take it "working out of the box" doesn´t include installing packages, just loading them?

library(tidyverse)
df <- mutate(df, my_vector_2)
str(df)

# Use filter() to print rows of your data frame greater than the median value of my_vector.
## Henrik: I thought the assignment was a bit unclear, but I read it as "print rows for which the value of my_vector is larger than the median of my_vector"
df %>% 
 filter(my_vector > median(my_vector))

```
